name: Project Data to Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  copy-build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
    - name: Ensure Clean Jupyter Notebooks
      uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@1.1
      with: 
        disable-checks: # optional, default is 
    - name: Copy Repository Contents
      run: |
          chmod -R 777 docs/docs
          ./action_files/copy_files.sh
    - name: setup directories for Jekyll build
        run: |
          cd docs
          rm -rf _site
          sudo chmod -R 777 .
    - name: Jekyll build
        uses: docker://jekyll/jekyll
        with:
          args: /bin/bash -c "cd docs; bundle install; bundle exec jekyll build"      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs/_site
